name: Bug Report
description: Report a bug or unexpected behavior in the front end.
title: '[BUG] - '
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the following details to help us investigate and resolve the issue.
  - type: input
    id: branch_name
    attributes:
      label: Branch Name
      description: Suggested branch name for fixing this issue
      placeholder: fix/[issue-id]
      value: fix/
    validations:
      required: true
      pattern: '^fix/[a-z0-9-]+$'
  - type: dropdown
    id: bug_type
    attributes:
      label: Bug Type
      description: Select the type of frontend bug you're reporting
      options:
        - UI/UX
        - Integration
        - Validation
        - Performance
        - Accessibility
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug.
      placeholder: 'Describe what the bug is.'
    validations:
      required: true
  - type: textarea
    id: design_reference
    attributes:
      label: Design Reference
      description: If applicable, provide any design mockups, wireframes, or references that illustrate your bug idea.
      placeholder: 'Upload images or provide links to design references that support your bug report.'
    validations:
      required: false
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the steps needed to reproduce the issue.
      placeholder: "1. Go to...\n2. Click on...\n3. See the error."
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: 'Describe the expected behavior.'
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: 'Describe the actual behavior you observed.'
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      placeholder: 'e.g., OS: Windows 10, Browser: Chrome 112, Release Version: 1.0.0'
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs or Console Output
      description: Paste any relevant logs or console output here. It will automatically be formatted.
      placeholder: 'Paste logs or error messages here.'
      render: shell
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the issue.
      placeholder: 'Provide any other relevant information here.'
    validations:
      required: false
